### ISSUE TITLE
Side folding ALG variants 

### ISSUE THREAD

**Issue by Airman42** [shadowmage45/KerbalFoundries2#13]
Hello Shadowmage, i mentioned this topic in Airplanes Plus page about the side folding ALG, and if its possible and if you have the time, could you create side folding ALG that have 2 wheels like the B737 or A320 and a 3 wheel like the B777. Thank you for your hard work and time  :)

**Comment by shadowmage45** [comment]
Thanks for opening up the issue ticket for this.  About the only way that I'll remember to investigate/work on it.

Currently it looks like I might be able to get to looking at these in a week or two, possibly for the first of the KSP 1.3 releases for KF/KSPWheel.
