### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by LeytanElectronics** [shadowmage45/KerbalFoundries2#19]
I downloaded this mod on 8/1/2017 but nothing works, the wheels won't move, caterpillar tracks won't move, hover engines won't hover, nothing in the mod will do anything. Am I missing something in the mod or what? Because I don't know how to trouble shoot this problem because I don't know what caused this issue.

**Comment by shadowmage45** [comment]
Did you install both ModuleManager and KSPWheels?  (both are dependencies included in the KerbalFoundries download/.zip file).

Otherwise, I will need log files in order to start diagnosing things (the KSP.log from your main KSP directory).

**Comment by LeytanElectronics** [comment]
according to the file there is no kspwheel or the modulemanager. their missing from the zip file.

**Comment by shadowmage45** [comment]
They are included in the .zip file.  Make sure to install them both.

**Comment by LeytanElectronics** [comment]
i found them, for some reason they never came over with the rest of the mod. o3o

**Comment by shadowmage45** [comment]
Is it all working for you (more or less) now that you have the dependencies installed?

**Comment by LeytanElectronics** [comment]
one moment to test.

**Comment by LeytanElectronics** [comment]
yep its working now.

**Comment by shadowmage45** [comment]
Glad that got it all working for you.

Please let me know if you run into any other issues with the mod (by opening up a new issue ticket with the relevant details).

**Comment by LeytanElectronics** [comment]
can do.
