### ISSUE TITLE
Landing gear retracting on take-off requires 2 presses of the "g" key

### ISSUE THREAD

**Issue by TheKurgan** [shadowmage45/KerbalFoundries2#22]
Not a big issue at all, but it was suggested I post it here. Only seen in the large and medium landing gear

**Comment by shadowmage45** [comment]
Thanks for taking the time to file the issue ticket -- it is the only way I can keep things organized.

Strange that it would only occur on the large and medium gear.  Can you confirm that the issue is not present on the small gear?

Either way, will take a look at this at the next opportunity for me to do coding/testing work.  Might be over this weekend, but still a bit unsure as to my schedule....

**Comment by TheKurgan** [comment]
I'll have a look when I get home, but the only landing gear I use are those two. I'll test the rest.

**Comment by TheKurgan** [comment]
Tested the Adjustable landing gear, from large to small, they all seem to have the same issue.
I tested the HDG (Heavy Duty) landing gear, and they do not seem to have this issue.

**Comment by shadowmage45** [comment]
I'm not sure where the 'Heavy Duty' landing gear are from... is that a stock or other mods' part?
(in which case... different plugins and all... can be no real comparison between the parts)

**Comment by TheKurgan** [comment]
My apologies, they are from B9 Aerospace Legacy... I thought they were from KF.

**Comment by shadowmage45** [comment]
No worries, was just trying to figure out what part was 'working' when the rest weren't.

I believe what this problem boils down to is the stock code --  the stock action group code examines all wheels on the vessel and sets the action-group gear button starting state to the most prevalent state among the wheels on the craft.  Obviously this only works with stock wheels, as the stock code ignores KSPWheel equipped parts.

More importantly, I'm not sure that I'll be able to override that stock behavior.  Will look though.

**Comment by TheKurgan** [comment]
No problem, I just thought I'd let you know about it. It's not a big deal at all, 
Don't waste too much of your time chasing it. Thank you so much for your time.
Cheers.

**Comment by TheKurgan** [comment]
Just a thought, the landing legs in KF seem to work fine, deploying and retracting with a single click. Are landing gear handled the same way in the stock code?

**Comment by shadowmage45** [comment]
Ahh... hmm...
ALG parts (the landing gear) use separate (and very specialized) modules from the landing legs.

Knowing that bit though -- I can look at the landing-leg code to see how I fixed it up there.  Should, in theory, be able to copy the working code from the landing-legs over to the landing gear.

(note though, that any 'standard' landing gear would use the same modules as the landing legs, and should probably work okay; the ALG parts are far from 'standard' though).

Thanks for pointing that bit out :)    I obviously have too much code to keep it all straight...

**Comment by shadowmage45** [comment]
Should be 'fixed' by https://github.com/shadowmage45/KSPWheel/commit/621aa4bd9a1d0492b56a464b4915346b0b839915 -- though I'm unable to test for a few more days.

Notably, this is not a full and proper solution, but is the same 'fix' that is used by the KF- landing gear.  Basically if a vessel has a mix of wheels in both deployed and retracted states, the last wheel/leg to run its init will set the state of the action group button.

**Comment by shadowmage45** [comment]
Will need to think up a proper solution that keeps the state of the action-group button, while also keeping the state of the wheels, all while setting the AG button to its intended state when the vessel is first placed onto the launchpad (or otherwise the first time it is in flight scene).

**Comment by TheKurgan** [comment]
Awesome, thanks, I could test it if it's available to download.

**Comment by TheKurgan** [comment]
Just saw this on Ferram Aerospace Research change log:

CHANGELOG

0.15.9V "Liebe"------------------------------------

Update for KSP 1.3
Update to MM 2.8.1

Include support for localization
Include German (by terorie), Russian (by pand5461), and Chinese (by Nigh) translations

Fix NaN errors with Trajectories
**Fix some issues with identifying KSPWheel Adjustable Landing Gear as gear**

Is this something related at all? Probably not hey.

**Comment by shadowmage45** [comment]
Only related insomuch as I was helping fix some bits in KSPWheel that were preventing FAR from working on the ALG parts (and still have a couple small bits to cleanup).    ( https://github.com/shadowmage45/KSPWheel/issues/47 )
