### ISSUE TITLE
ALG Medium doesn't retract.

### ISSUE THREAD

**Issue by Taris9047** [shadowmage45/KerbalFoundries2#23]
In fact, it retracts but the animation doesn't work. Its steering animation does not work either.

Just downloaded the 2.0.2.8 version from release.

Addendum: ALG small gears work fine. Even retracts with a single type of 'g' key. Prolly connected to the hit 'g' key twice to retract issue?

**Comment by shadowmage45** [comment]
Steering only works when the wheel strut angle is set to < 1 degree.  Are your struts angled or straight?  (this is to only enable steering for 'front' wheels)

Should not be any difference in functionality between the small and medium (or large) gears; they all use the same code and config setup (mostly, aside from transform names).  Will attempt to do some testing on this today to see if I can confirm the animation problem.

**Comment by Taris9047** [comment]
I did not touch any angle setting since it was installed as a front wheel of an aircraft. It should be centered by default, right?

But then again it steers. Yet the steering animation does not play. Same as retracting and lowering the gear. It retracts (aircraft nose touches the floor if I try to retract the gear) but the animation does not work.

**Comment by shadowmage45** [comment]
I cannot confirm the 'does not retract' issue.  When I add one of the ALG in the editor (any one) it seems to work fine; I can press the 'toggle gear' action buttion all day long, and it plays the retract/deploy animation just fine.

![screenshot4](https://user-images.githubusercontent.com/1503399/29797615-7939f8c4-8c15-11e7-8aec-1da13d752cea.png)

![screenshot0](https://user-images.githubusercontent.com/1503399/29797637-978e5a54-8c15-11e7-85f5-b314acae7e39.png)

![screenshot1](https://user-images.githubusercontent.com/1503399/29797638-99056170-8c15-11e7-9aeb-e0b704b67b8f.png)

Is there a specific set of actions / state / etc needed to trigger this problem?

**Comment by Taris9047** [comment]
![screenshot32](https://user-images.githubusercontent.com/2917032/29798020-fc7532f8-8c1f-11e7-8ba9-9b97cc8c37b1.png)
On the ground, right after loaded

![screenshot34](https://user-images.githubusercontent.com/2917032/29798026-0f9cd192-8c20-11e7-8473-16cd04fa1f6a.png)
when 'g' key pressed. rear wheels bounce off like crazy, yet the nose wheel doesn't retract but descends into the floor.

![screenshot36](https://user-images.githubusercontent.com/2917032/29798044-30f80b2c-8c20-11e7-9514-732a801c16e0.png)
End result. the nose wheel still clips through the floor.


ps. the animation works fine in the SPH.

**Comment by Taris9047** [comment]
000_AT_Utils/
000_Toolbar/
ActiveTextureManagement/
AirPark/
AirplanePlus/
AoATech/
ASET/
AviationCockpits/
B9_Aerospace/
B9AnimationModules/
B9PartSwitch/
BahaSP/
BDArmory/
BDMk22/
Blue_Hawk_Industries/
BurnTogether/
CAL/
ConfigurableContainers/
ContractConfigurator/
DestructionEffects/
Diazo/
EjectionSeatsToAll.cfg*
Firespitter/
FShangarExtender/
HullBreach/
ImprovedChaseCamera/
JSI/
KerbalEngineer/
KerbalFlightIndicators/
KerbalFoundries/
KerbalJointReinforcement/
KerbalKonstructs/
KerbinSide/
KSPWheel/
list*
LShipPartsModern/
MechJeb2/
MechJebAndEngineerForAll.cfg*
MM_README.md*
ModuleManager.2.8.1.dll*
ModuleManager.ConfigCache*
ModuleManager.ConfigSHA*
ModuleManager.Physics*
ModuleManager.TechTree*
ModuleManagerLicense.md*
MouseAimFlight/
MTW/
North Kerbin Weaponry/
P.E.W/
PhysicsRangeExtender/
Pilot Assistant/
ProceduralDynamics/
ProceduralParts/
QuizTechAeroContinued/
SCANsat/
scatterer/
SM_Armory/
SM_Industries/
SM_Industries.cfg*
SM_Marine/
SmokeScreen/
Squad/
TakeCommand/
TarisParts/
TarisParts.zip*
TextureReplacerReplaced/
toolbar-settings.dat*
TweakScale/
VanguardTechnologies/
VesselMover/
VesselView/
WaypointManager/

File list in my mod folder. TarisParts is my own edit for somewhat powerful engines, based on stock parts. Didn't touch any .dll files or anything like that.

I'm running Windows 64bit version on Windows 10.

**Comment by Taris9047** [comment]
craft file

**Comment by Taris9047** [comment]
[A-4A Attack Hawk.craft.txt](https://github.com/shadowmage45/KerbalFoundries2/files/1258690/A-4A.Attack.Hawk.craft.txt)
Craft file.

**Comment by Taris9047** [comment]
Tested with a simple craft. (crafted at SPH)

![screenshot39](https://user-images.githubusercontent.com/2917032/29798471-b2586f52-8c22-11e7-9a42-93b9f26f6543.png)
At start.

![screenshot40](https://user-images.githubusercontent.com/2917032/29798473-b3cf718c-8c22-11e7-9fb1-f5e8af6a7d77.png)
'g' key pressed.

![screenshot41](https://user-images.githubusercontent.com/2917032/29798476-b57499e0-8c22-11e7-8f95-2415dd859792.png)
One wheel remains stretched...


**Update:**
Reverted flight to launch.
All wheels retracted correctly.

**Comment by shadowmage45** [comment]
Thanks for the craft file and examples.  When testing with the example craft from above (stock pod + 4 wheels), I can confirm there is an issue if the craft is launched with the wheels in the deployed state.  

Doesn't appear to be specific to the medium-alg though, but effects any/all deployable parts using the KSPWheels modules for deployment when launched in the deployed state (all ALG, stock patched parts, SSTU/etc).

Looking into this now, would seem likely that it is caused by the action-group updating code triggering the action group on as-yet uninitialized parts.  Will update with more info as I figure it out.

**Comment by Taris9047** [comment]
Yeah, it doesn't seem to be ALG-Medium problem. Just tested 4 ALG-Large and 4 ALG-small on the same simple craft, one ALG-small didn't retract.

![screenshot43](https://user-images.githubusercontent.com/2917032/29798795-eaac42e6-8c24-11e7-9df3-296d865b90a0.png)

Thanks for following up.

**Comment by shadowmage45** [comment]
Seems to be working much better now, no log-spam, and all the wheels deploy/retract like they should.

As this is a fairly critical bug that prevents proper use of the ALG (and other deployable) parts, I'll be putting together an updated release shortly (tonight for KSPWheel, likely tomorrow for KF and others).  

For the time being, you could try using the updated/fixed .dll from:  ( https://github.com/shadowmage45/KSPWheel/raw/dev/GameData/KSPWheel/Plugin/KSPWheel.dll )  ( click to download, replace the existing one in GameData/KSPWheels/Plugin/ )

**Comment by Taris9047** [comment]
Works like a charm! Made me play [https://www.youtube.com/watch?v=KngRgfP2YkQ&t=30s](url)

Thanks!!
