### ISSUE TITLE
crashing ksp

### ISSUE THREAD

**Issue by Bushelfoot** [shadowmage45/KerbalFoundries2#26]
[error.log](https://github.com/shadowmage45/KerbalFoundries2/files/1537835/error.log)

This is my first post on here, not sure I did it right. KSP Wheel is crashing my game. The game still loads with KF installed but not with KSP Wheel.

I'm adding the beginning of the crash file since I don't think it uploaded the way I needed. 
Unity Player [version: Unity 5.4.0p4_b15b5ae035b7]

mono.dll caused an Access Violation (0xc0000005)
  in module mono.dll at 0033:e6cb0e6a.

Error occurred at 2017-12-06_222654.
E:\SteamLibrary\steamapps\common\Kerbal Space Program\KSP_x64.exe, run by Daniel.
60% memory in use.
8192 MB physical memory [3260 MB free].
16381 MB paging file [10983 MB free].
8388608 MB user address space [8386330 MB free].
Read from location 00000010 caused an access violation.

Context:
RDI:    0x00000000  RSI: 0x33d4f740  RAX:   0x00000000
RBX:    0x00000007  RCX: 0xab8c0000  RDX:   0x0017e7e0
RIP:    0xe6cb0e6a  RBP: 0x0017e8e0  SegCs: 0x00000033
EFlags: 0x00010202  RSP: 0x0017e7e0  SegSs: 0x0000002b
R8:    0x8775bfa0  R9: 0x00000054  R10:   0x00000002
R11:    0x0017e770  R12: 0x877b20e0  R13:   0x00000054
R14:    0x4d0b3050  R15: 0x00000001

**Comment by shadowmage45** [comment]
Are you trying to use KSP 1.3.0?

A crash like that will occur on unsupported KSP versions.  KF + KSPWheel only support KSP 1.3.1.
