### ISSUE TITLE
the rover wheels, not sure what the name, doesn't count as "on motorized wheels" in contracts..

### ISSUE THREAD

**Issue by aaronsta1** [shadowmage45/KerbalFoundries2#28]
im trying to make a base that has the requirement "on motorized wheels" and none of the rover wheels qualify.. im still going to use them, just have to cheat the contract finished..

**Comment by shadowmage45** [comment]
Going to need to know at least the name of the part you were using....

But shouldn't be a problem to get it fixed up after that is posted.

**Comment by aaronsta1** [comment]
it was the KF Medium Wheel. but i didnt test the other ones..

**Comment by shadowmage45** [comment]
That should give me enough info to get started.  Likely is a problem with the other wheels as well, as I don't think I've explicitly handled the 'motorized' contract objective.

Thankfully, should also be fairly simple to solve by adding the proper method override/return to the KSPWheelMotor module.
