### ISSUE TITLE
Sound improvements

### ISSUE THREAD

**Issue by docmop** [shadowmage45/KerbalFoundries2#4]
This should be considered as improvement suggestion.

Separate Sounds for rolling, motor and wheelslip (for  reference, there is a WheelSound mod in the forums which is quite excellent). Currently wheels are silent when not accelerating.

http://forum.kerbalspaceprogram.com/index.php?/topic/50431-12-rover-wheel-sounds-v23-2016-10-24/#comment-719277

**Comment by shadowmage45** [comment]
Separate controllable effects already exist for each of those (motor, running, slips):
https://github.com/shadowmage45/KSPWheel/blob/master/VSProject/KSPWheel/PartModules/KSPWheelSounds.cs#L13-L34

The main problem I have with doing any further sounds-related work, is the lack of available truly-free sound effects (completely free of any license encumbrance, in the public domain).  I am not a sound-artist, and would not even know where to begin on creating custom sound effects, and my searches for public-domain sounds have never led anywhere.

The -first- problem that needs to be solved is the lack of sound-effect files.  After that is solved, the rest is easy...

Edit:
I'll take a look at how usable the existing sounds are in KF for different effects.  I don't think the existing slip effect will work as it is non-loopable, but there might be two that I can use as separate motor and running/speed sounds.  If they are usable for the purposes all that is needed is to write up the config effect nodes.

**Comment by docmop** [comment]
Splendid. If that doesn't work out though, maybe consider just adding support for the mod mentioned earlier.

**Comment by shadowmage45** [comment]
Have adapted a couple of the existing KF sounds to give a different sound between motor and rolling effects.  Will be available in an update later today.

As far as the 'wheel sounds' mod goes -- I cannot add support on this end, it would need to be added on the 'Wheel Sounds' mods' end (as it is hard-coded for stock wheels, I cannot possibly make it work for KSPWheel setup).
