### ISSUE TITLE
Surface-mount hoverpads don't work

### ISSUE THREAD

**Issue by Fireheart318** [shadowmage45/KerbalFoundries2#6]

**Comment by shadowmage45** [comment]
They work just fine for me.... (see image below of surface-repulsors working just fine)

![screenshot4](https://cloud.githubusercontent.com/assets/1503399/22622446/97160ee2-eaf7-11e6-8d9a-5a0f84b3bc06.png)



Pics of the craft you are having problems with, and log files might be needed on this one.
