### ISSUE TITLE
Tracks bouncy, jumping, exploding since KSPWheel 0.9.2.10

### ISSUE THREAD

**Issue by Haifirion** [shadowmage45/KerbalFoundries2#8]
I've tried several re installs with different version combinations of KF and KSPWheel. KF 2.0.0.1 and KSPWheel 0.9.2.9 work fine, but with 0.9.2.10 with standard settings, the tracks bounce around higher and higher until they explode, even on lowest spring setting you can see the tracks hopping up and down a bit.
Also there are 2 tracks that wont brake in both KF releases, the "small track" and "rbi inverting track".

**Comment by shadowmage45** [comment]
Could you provide pics of the craft in question (that has bouncy/jumpy tracks)?

There are still a few issues I'm sorting through regarding joints and rigidity; I've noticed that when wheels are mounted at the end of a long chain of parts that they like to jitter a bit (this is why stock wheels use autostruts).

There is also the spring calculation issues that I had mentioned in one of the threads; the more wheels you have on a craft, the less compressed they will all be; at <0.2 compression it can start to cause jitter -- which can cause problems with tracks especially as they all use 'lots of wheels'.

Brakes -- Will take a look.  Was working when I last tested it.

**Comment by shadowmage45** [comment]
I'm not getting any bouncing or jumping, or exploding.

![screenshot5](https://cloud.githubusercontent.com/assets/1503399/22622474/9491f8c4-eaf8-11e6-83df-4cd44e2fcf32.png)


Going to need logs and at least pics of the craft.

**Comment by shadowmage45** [comment]
Have fixed the problems with brakes, should be working with the next KF release.

**Comment by shadowmage45** [comment]
Have also tracked down and fixed -a- problem with tracks and bouncy/jitteriness (improper mass allocation for suspension calculation).  However it was not present on the small tracks which is what I was initially using for testing.

**Comment by shadowmage45** [comment]
If your problems are not solved with the next release, please open a new issue and include logs and at least pics of the craft (or .craft files if it is all stock/KF).
